#!/bin/bash
# $Id: mkinitramfs-ll/mkifs-ll_gpg[.bash],v 0.1.2 2011/10/30 -tclover Exp $

usage() {
   cat << EOF
   usage: ${0##*/} [OPTINS]...
      --useflags="flags" extra USE flags to append to USE="nls static"
      --Version=<STR>	 build gpg-<STR> version instead of gpg-1.4.x
  -u, --usage            print this help/uage and exit
EOF
}

while [[ $# > 0 ]]; do
	case $1 in 
		--useflags=*) EUSE="${1#*=}"; shift;;
		--Version=*) Version=${1#*=}; shift;;
		--usage|-u|*) usage; exit 0;;
	esac
done

[[ -f ./mkifs-ll.conf ]] && source ./mkifs-ll.conf
:	${WORKDIR:=$(pwd)}
:	${MISCDIR:=$WORKDIR/misc}
:	${BINDIR:=$WORKDIR/bin}

error() { echo -ne "\e[1;31m* \e[0m$@\n"; }
die() { error "$@"; exit 1; }

mkdir -p "$BINDIR"

cd ${PORTDIR:-/usr/portage}/app-crypt/gnupg || die "eek"
GPG=$(emerge -pvO =app-crypt/gnupg-${Version:-1.4*}|grep -o "gnupg-[-0-9.r]*")
USE="nls static $EUSE" ebuild $GPG.ebuild compile || die "eek!"
cd "${PORTAGE_TMPDIR:-/var/tmp}"/portage/app-crypt/$GPG/work/$GPG || die "eek!"
cp -a gpg "$BINDIR"/ || die "eek!"
cp g10/options.skel "$BINDIR"/ || die "eek!"
cd "${PORTDIR:-/usr/portage}"/app-crypt/gnupg || die "eek"
ebuild $GPG.ebuild clean || die "eek!"
cd "$WORKDIR" || die "eek!"

set iGPG=y
unset GPG EUSE Version

# vim:fenc=utf-8:ci:pi:sts=0:sw=4:ts=4:
