.\"
.\" CopyLeft (c) 2015 -tclover <tokiclover@gmail.com>
.\"
.\" Distributed under the terms of the 2-clause BSD License as
.\" stated in the COPYING file that comes with the source files
.\"
.pc
.TH MKINITRAMFS-LL 8 "2015-01-14" "0.16.3" "Build Script Page"
.SH NAME
mkinitramfs-ll \- tool for building initramfs
.SH DESCRIPTION
.B mkinitramfs-ll
is an initramfs building script. It requires
.IR mkinitramfs-ll.conf
configuration file and the associated
.IR usr\ [USRDIR]
directory to complete the task. Those two requirements are not
.IR scrictly
necessary, but are
.IR necessary
to build a
.IR functionnal
initramfs.

It also require `/lib/modules/$KV' kernel object directory along with its
`modules.dep' file, or else, no kernel module would be added. Fonts should
be available in `/usr/share/consolefonts'; Keymaps in `/usr/share/keymaps';
splash Themes in `/etc/splash'; Firmwares in `/lib/firmware'; Binaries in `$PATH';
Or else, use full path to file instead.

Aything can be bundled directly in USRDIR for convenience for the end user.
However, it's useless to waste disk space if the files are available in a live system.
Editing the configuration file should suffice in most cases.

If executed without arguments, an initramfs would be build for the current kernel
with the default options defined in the configuration file.
.SH CONFIGURATION
.B mkinitramfs-ll.conf
is the general purpose configuration file of this tool. Every command line
.IR switch
can be used, minus a hyphen for the long variant, as a key in the associative array
.IR opts
like
.IR opts[-option]=VALUE
to modify the behaviour of the tool. Extra configuration variables
are also available. See the configuration file for more info.
.SH SYNOPSIS
.br
.B mkinitramfs-ll
.RB [\| OPTIONS \| ]

.br
.B mkinitramfs-ll
.RB [\| \-a|\-\-all \|]
.RB [\| \-f|\-\-font=: \|\c
.RI [\| regex \|]\|]
.RB [\| \-F|\-\-firmware=: \|\c
.RI [\| regex \|]\|]
.RB [\| \-k|\-\-kv= \|\c
.RI \| version \|]
.RB [\| \-c|\-\-compressor= \|\c
.RI \| comp \|]
.RB [\| \-L|\-\-luks \]
.RB [\| \-l|\-\-lvm \]
.RB [\| \-b|\-\-bin=: \|\c
.RI [\| binary \|]\|]
.RB [\| \-d|\-\-usrdir= \|\c
.RI \| directory \|]
.RB [\| \-g|\-\-gpg \|]
.RB [\| \-p|\-\-prefix= \|\c
.RI \| initrd- \|]
.RB [\| \-H|\-\-hook=: \|\c
.RI \| regex \|]
.RB [\| \-m|\-\-kmod=: \|\c
.RI \| regex \|]
.RB [\| \-\-mtuxonice=: \|\c
.RI \| regex \|]
.RB [\| \-\-mremdev=: \|\c
.RI \| regex \|]
.RB [\| \-\-msquashd=: \|\c
.RI \| regex \|]
.RB [\| \-\-mgpg=: \|\c
.RI \| regex \|]
.RB [\| \-\-mboot=: \|\c
.RI \| regex \|]
.RB [\| \-s|\-\-splash=: \|\c
.RI \| theme \|]
.RB [\| \-t|\-\-toi \|]
.RB [\| \-q|\-\-squashd \|]
.RB [\| \-r|\-\-rebuild \|]
.RB [\| \-y|\-\-keymap=: \|\c
.RI \| regex \|]
.RB [\| \-K|\-\-keep-tmpdir \|]

.br
.B mkinitramfs-ll
.RB [\| \-?|\-h|\-\-help \|]

The following conventions apply to
.B SYNOPSIS
section and can be applied to the command line arguments.
.TS
tab (@);
l lx.
\fIitalic text\fR@T{
replace with appropriate argument.
T}
[\|\fB\-short\fR|\fB\-\-long\fR\|]@T{
any or all argument within [ ] are optional; and short or long option can be used.
T}
\fB\-short\fR|\fB\-\-long=:argument\fR@T{
option starting with a colon accepts a colon separated list of argument
T}
\fIregex\fR@T{
replace regex with a regular expression, matching regex will be performed.
T}
\fBUSRDIR\fR@T{
refer to `usr' directory (in `/' of the source files or DATADIR/mkinitramfs-ll/usr)
T}
.TE

.SH OPTIONS
.TP
.B \-a|\-\-all
short variant or form of `\-\-font=: \-\-keymap=: \-\-luks \-\-lvm \-\-gpg
\-\-hook=:btrfs:zfs:zram \-\-toi \-\-squashd'
.TP
.B \-f|\-\-font=:[\fIregex\fR]
include a colon separated list of font either a full path or a name
relative to `/usr/share/consolefonts' (or nothing would be included)
.TP
.B \-F|\-\-firmware=:[\fIregex\fR]
include a colon separated list of firmware either a full path or a name
relative to `/lib/firmware' (or nothing would be included)
(`:' would add the whole firmware directoy)
.TP
.B \-k|\-\-kv=[\fIversion\fR]
linux kernel version to use for building an initramfs
.TP
.B \-c|\-\-compressor=[\fIcomp\fR]
compressor to use for compression or `none' for uncompressed initramfs
.TP
.B \-L|\-\-luks
enable dm-crypt LUKS support (require cryptsetup)
.TP
.B \-l|\-\-lvm
enable device-mapper support (require lvm2)
.TP
.B \-b|\-\-bin=:[\fIbinary\fR]
include a colon separated list of binary to the initramfs
.TP
.B \-d|\-\-usrdir=\fIdirectory\fR
use the appended directory as (USRDIR) `usr' directory
.TP
.B \-g|\-\-gpg
enable GnuPG support (require gnupg-1.4.x)
.TP
.B \-p|\-\-prefix=initrd-
use `initrd-' prefix to name initramfs
.TP
.B \-H|\-\-hook=:[\fIregex\fR]
include a colon separated list of hooks or scripts to the initramfs
.TP
.B \-m|\-\-kmod=:[\fIregex\fR]
include a colon separated list of kernel module to the initramfs
.TP
.B \-\-mtuxonice=:[\fIregex\fR]
append a colon separated list of kernel module to tuxonice group
.TP
.B \-\-mremdev=:[\fIregex\fR]
append a colon separated list of kernel module to remdev group
.TP
.B \-\-msquashd=:[\fIregex\fR]
append a colon separated list of kernel module to remdev group
.TP
.B \-\-mgpg=:[\fIregex\fR]
append a colon separated list of kernel module to gpg group
.TP
.B \-\-mboot=:[\fIregex\fR]
append a colon separated list of kernel module to boot group
.TP
.B \-s|\-\-splash=:[\fItheme\fR]
include a colon separated list of splash theme (require splashutils)
.TP
.B \-t|\-\-toi
enable TuxOnIce support (require tuxonice-userui for splash)
.TP
.B \-r|\-\-rebuild
rebuild an initramfs from an existant directory
.TP
.B \-y|\-\-keymap=:[\fIregex\fR]
.br
include a colon separated list of console keymap either a full path or name
relative to `/usr/share/keymaps' (or nothing would be included)
.TP
.B \-K|\-\-keep-tmpdir
keep the temporary build directory
.TP
.B \-?|\-h|\-\-help
print the help message and exit
.TP
.B RAID (FAKE ATA & SOFWARE)
just append the appropriate binary, that is
.IR dmraid
or
.IR mdadm
with `-b|--bin' switch,
to enable either dm-raid (fake ATA RAID) or mdadm software RAID
.TP
.B HOOKS & USER SCRIPTS
Any hook or script should be in `USRDIR/../hooks', so `-H|--hook' switch would
rightly add any appended hook (if any.) If `opts[-b$SCRIPT]' & `opts[-m$SCRIPT]'
are defined in the configuration file, the binaries, kernel module & group would
be added.
.TP
.B BTRFS, BCACHE, ZFS & ZRAM SUPPORT
To enable support for any of either bcache, btrfs, zfs & zram,
append `-H|--hook' with a colon separated list of hooks (`-H:$HOOKS'.)
.SH EXAMPLES
.TP
.BI mkinitramfs-ll\ \-\-all\ \-\-font=ter-g12n\ \-\-keymap=fr\ \-\-firmware=nouveau:iwlwifi-5000\ \-\-kv=3.14.26-git
Build an initramfs with
.B GnuPG, LUKS, LVM2,
.B BTRFS, ZFS,
.B zram, AUFS+SquashFS support for
linux kernel 3.14.26-git; nVidia and iwlWIFI-5000 firmwares are included as well.
.SH ENVIRONMENTS
.TP
.B MIR_EXTRA_ENV
This environment variable would be used, if set, to generate the environment
variables of
.IR init
script.
.SH FILES
.TP
.I [SYSCONFDIR/]mkinitramfs-ll.conf
mkinitramfs-ll configuration file.
(SYSCONFDIR should be `/etc' in a standard installtion)
.TP
.I [DATADIR/mkinitramfs-ll/]usr
mkinitramfs-ll
.IR usr
directory that contains extra files, e.g.
.IR functions
(library like) file, for initramfs.
(DATADIR should be `/usr/share' in a standard installtion)
.TP
.I USRDIR/../scripts/minimal.applets
busybox minimal applet list (compatibility)
.SH "SEE ALSO"
.BR mkinitramfs-ll (1)
.SH AUTHORS
-tclover <tokiclover@mkinitramfs-ll.project>
.\"
.\" vim:fenc=utf-8:ft=groff:ci:pi:sts=2:sw=2:ts=2:expandtab:
.\"
