#!/bin/sh
# $Id: mkinitramfs-ll/xcpio, 2012/06/18 12:05:45 -tclover Exp $
[ -z "$@" ] && echo "usage: ${0##*/} -l|-i files" && exit 1
case $1 in
	-l|-ls|-list) opt=-t; shift;;
	-x|-*xtract)  opt=-i; shift;;
	*) opt=-t;;
esac
for file in $@; do
	case ${file##*.} in
		bz*2)	comp=bzcat;;
		gz*) 	comp=zcat;;
		xz) 	comp=xzcat;;
		lzma)	comp=xzcat;;
		lzo*)	comp=lzop -cd;;
		lz*)	comp=lzip -cd;;
		*) echo "unsupported compression format"; exit 1;;
	esac
	$comp $file | cpio $opt
done
unset -v opt comp
# vim:fenc=utf-8:ci:pi:sts=0:sw=4:ts=4:
