#!/bin/sh
#
# $Header: mkinitramfs-ll/scripts/swsuspend              Exp $
# $Author: (c) 2011-2014 -tclover <tokiclover@gmail.com> Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
# $Version: 2014/09/14 12:33:03                          Exp $
#

usage() {
	cat <<-EOH
 usage: swsuspend [-o|--option platform|shutdown ] [major:minor]
   -o, --option platform|shutdown    set suspend mode (ACPI/shutdown)
   -s, --size N                      set image size to N bytes
   -h, --help                        print this help message
EOH
}

while [ $# > 1 ]; do
	case "$1" in
		(-o|--option)
			option=$2
			shift 2;
		(-s|--size)
			size=$2
			shift 2;;
		(-h|--help)
			usage
			exit;;
	esac
done
:	${option:=platform}

[ $# = 1 ] &&
echo $1       > /sys/power/resume
echo $option  > /sys/power/disk
echo disk     > /sys/power/state
[ -n "$size" ] &&
echo $size    > /sys/power/image_size

unset option size

#
# vim:fenc=utf-8:ci:pi:sts=0:sw=4:ts=4:
#
