#!/bin/sh
# $Id: mkinitramfs-ll/xcpio, 2014/08/08 10:56:45 -tclover Exp $

[[ -z "$@" ]] && echo "usage: ${0##*/} [{-l|-list}|{-x|-extract}] files" && exit 1

comp() {
	local comp o
	case $1 in
		*.bz*2) comp=bzcat;;
		*.gz*) comp=zcat;;
		*.xz) comp=xzcat;;
		*.lzma) comp=xzcat;;
		*.lzo*) comp='lzop -cd';;
		*.lz4) comp='lz4 -d' o=-;;
		*.lz*) comp='lzip -cd';;
		*) echo "xcpio: unsupported compression format"; exit 2;;
	esac
	$comp $1 $o
}

case $1 in
	-l|-ls|-list) opt=-tv
		shift;;
	-x|-*xtract) opt=-idv
		shift;;
	*) opt=-t;;
esac

for file in $*; do
	if [ -f "$file" ]; then
		tmpdir=${file##*/}
		tmpdir=$(mktemp -d ${tmpdir%%.cpio*}-XXXXXX)
		cd $tmpdir || exit $?
		comp $file | cpio $opt &&
		echo "xcpio: successfuly deflated to $tmpdir"
	else
		echo "xcpio: $file file not found"
	fi
done

unset -v file opt tmpdir

# vim:fenc=utf-8:ci:pi:sts=0:sw=4:ts=4:
